data_ct_json_file: "./radiopaedia_abdomen_ct_image_annotated.json"
data_mri_json_file: "./radiopaedia_abdomen_mri_image_annotated.json"
pretrained_model_path: "./ckpt/"
logdir: "./train_unet/MRGen"
validation_sample_logger:
    num_inference_steps: 50
    guidance_scale: 7.0
gradient_accumulation_steps: 2
train_batch_size: 16
val_batch_size: 1
train_steps: 400000
validation_steps: 500
checkpointing_steps: 10000
seed: 6666
mixed_precision: 'fp16' # 'no'
learning_rate: 1e-5
lr_scheduler: "cosine"
# lr_scheduler: "constant"
# lr_scheduler: "linear"
use_8bit_adam: True