pretrained_model_path: "./ckpt/"
logdir: "./train_controlnet/MRGen"
validation_sample_logger:
    num_inference_steps: 50
    guidance_scale: 6.0
gradient_accumulation_steps: 1
train_batch_size: 32
val_batch_size: 1
train_steps: 40000
validation_steps: 500
checkpointing_steps: 5000
seed: 6666
mixed_precision: 'fp16' # 'no'
learning_rate: 1e-5
lr_scheduler: "cosine"
# lr_scheduler: "constant"
# lr_scheduler: "linear"
use_8bit_adam: True